apiVersion: v1
kind: Service
metadata:
  name: webapp-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: demo-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
